%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 1000
image_height: 625
distortion_parameters:
   k1: -0.00560245508
   k2: 0.00475728368
   p1: 0
   p2: 0
projection_parameters:
   fx: 448.6667739392236
   fy: 448.6667739392236
   cx: 500.0
   cy: 312
