%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam: 1  

# imu_topic: "/mavros/imu/data_raw"
imu_topic: "/world/iris_runway/model/iris_with_gimbal/model/gimbal/link/imu_link/sensor/imu_sensor/imu"
# imu_topic: "/imu/imu/data"
image0_topic: "/camera/image_raw"
# image0_topic: "/left/downsample_raw"
# image1_topic: "/right/downsample_raw"
output_path: "/home/snkt/output"

cam0_calib: "cam0_pinhole.yaml"
# cam1_calib: "cam1_pinhole.yaml"
image_width: 1000
image_height: 625
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   cols: 4
   rows: 4
   dt: d
   data: [0,-1,0,0.0105,
         1,0,0,-0.065,
         0,0,-1,0.002,
         0,0,0,1]

#  data: [ -7.7365220259020706e-02, 0.996116924643022, -0.0420201753209185, 0,
#             0.971314106478377, 0.0657991676472631, -0.228515592669382, 0,
#             -0.224863356842294, -0.0584939482053901, -0.972632987705517, 0,
#             0, 0, 0, 1]

#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.2          # accelerometer measurement noise standard deviation. 
gyr_n: 0.2         # gyroscope measurement noise standard deviation.     
acc_w: 0.002       # accelerometer bias random work noise standard deviation.  
gyr_w: 0.0002       # gyroscope bias random work noise standard deviation.     
    
g_norm: 9.8     # gravity magnitude

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: 0.0                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/snkt/output/pose_graph/" # save and load path
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
visualize_imu_forward: 1        # output imu forward propogation to achieve low latency and high frequence results
visualize_camera_size: 0.4      # size of camera marker in RVIZ
